# Generated by Django 5.0.6 on 2024-07-06 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_initial"),
        ("tasks", "0005_alter_task_description_alter_task_labels"),
    ]

    operations = []
